In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow

In [6]:
from tensorflow.keras.models import Sequential

In [7]:
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN

In [8]:
dfmovie=pd.read_csv(r"C:\Users\anand\OneDrive\PGA-54 TOOLS\DEEP LEARNING\Datasets\IMDB Dataset.csv")

NLP Pre Processing

remove html tags

In [9]:
import re

In [10]:
dfmovie['review']=dfmovie['review'].map(lambda x: re.sub("<.+?>", "", x))

remove the urls

In [7]:
dfmovie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
dfmovie['review']=dfmovie['review'].map(lambda x: re.sub("https?://|www.+", "", x))

Case folding

In [9]:
dfmovie["review"]=dfmovie["review"].map(lambda x: x.lower())

Contractions

In [10]:
import contractions

In [11]:
dfmovie["review" ]=dfmovie["review"].map(lambda x: contractions.fix(x))

Punctuation

In [12]:
import string

In [13]:
from string import punctuation

In [14]:
punc=punctuation

In [15]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
p1="""'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'"""

In [17]:
 dfmovie["review"]=dfmovie["review"].map(lambda x: "".join([c for c in x if c not in punctuation]))

Remove stop words

In [18]:
import nltk

In [19]:
from nltk.corpus import stopwords

In [20]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/chanakhya21/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [21]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [22]:
sw_eng=stopwords.words('english')

In [23]:
sw_eng

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [24]:
dfmovie["review"]=dfmovie["review"].map(lambda x: " ".join([w for w in x.split() if w not in sw_eng]))
dfmovie.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically family little boy jake thinks zombie...  negative
4  petter matteis love time money visually stunni...  positive

Stemming(destroying the word so performing lemmatization)

Lemmatization

In [25]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/chanakhya21/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [26]:
lemma=nltk.WordNetLemmatizer()

In [27]:
lemma.lemmatize("works")

'work'

In [28]:
dfmovie["review"]=dfmovie["review"].map(lambda x: " ".join([ lemma.lemmatize(w) for w in x.split()  ]))

In [29]:
dfmovie["review"].head()

0    one reviewer mentioned watching 1 oz episode h...
1    wonderful little production filming technique ...
2    thought wonderful way spend time hot summer we...
3    basically family little boy jake think zombie ...
4    petter matteis love time money visually stunni...
Name: review, dtype: str

NLP PIPELINE FUNCTION CODE (preprocessing)

In [30]:
def nlp_pipeline(data):

    data=data.map(lambda x: re.sub("<.+?>", "", x))                                     #remove html tags    
    data=data.map(lambda x: re.sub("https?://|www.+", "", x))                           #remove urls  
    data=data.map(lambda x: x.lower())                                                  #lowercase  
    data=data.map(lambda x: contractions.fix(x))                                        #expand contractions    
    data=data.map(lambda x: "".join([c for c in x if c not in punctuation]))            #remove punctuation
    data=data.map(lambda x: " ".join([w for w in x.split() if w not in sw_eng]))        #remove stopwords   
    data=data.map(lambda x: " ".join([ lemma.lemmatize(w) for w in x.split()]))         #lemmatization  
    return data                                                                         #return the cleaned data

#Tokenization

In [31]:
#1.Case Folding
#2.Word tokenization
#3.Extract Unique words
#4.provide Numerical representation for unique words
#5.Keep track of Each Unique Words absed on its Presence

In [32]:
dfmovie.shape

(50000, 2)

In [33]:
#get number of words present in each review 
dfmovie["review"].map(lambda x: len(x.split())).head()  
#get the maximum number of words in a review    
dfmovie["review"].map(lambda x: len(x.split())).max()   
#get the minimum number of words in a review    
dfmovie["review"].map(lambda x: len(x.split())).min()   
#get the average number of words in a review    
dfmovie["review"].map(lambda x: len(x.split())).mean()

np.float64(117.55736)

In [34]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [35]:
Tokenizer=Tokenizer(num_words=10000,oov_token="<OOV>")

In [36]:
Tokenizer

In [37]:
Tokenizer.fit_on_texts(dfmovie["review"])

In [38]:
Tokenizer.word_index

{'<OOV>': 1,
 'movie': 2,
 'film': 3,
 'one': 4,
 'like': 5,
 'would': 6,
 'time': 7,
 'good': 8,
 'character': 9,
 'get': 10,
 'even': 11,
 'story': 12,
 'make': 13,
 'see': 14,
 'really': 15,
 'scene': 16,
 'much': 17,
 'could': 18,
 'well': 19,
 'people': 20,
 'great': 21,
 'bad': 22,
 'also': 23,
 'show': 24,
 'first': 25,
 'way': 26,
 'thing': 27,
 'made': 28,
 'think': 29,
 'life': 30,
 'go': 31,
 'know': 32,
 'watch': 33,
 'love': 34,
 'many': 35,
 'seen': 36,
 'actor': 37,
 'two': 38,
 'plot': 39,
 'say': 40,
 'never': 41,
 'look': 42,
 'acting': 43,
 'end': 44,
 'little': 45,
 'best': 46,
 'year': 47,
 'ever': 48,
 'better': 49,
 'take': 50,
 'man': 51,
 'come': 52,
 'still': 53,
 'work': 54,
 'want': 55,
 'find': 56,
 'part': 57,
 'something': 58,
 'give': 59,
 'lot': 60,
 'cannot': 61,
 'back': 62,
 'u': 63,
 'director': 64,
 'real': 65,
 'guy': 66,
 'watching': 67,
 'performance': 68,
 'play': 69,
 'going': 70,
 'woman': 71,
 'though': 72,
 'actually': 73,
 'funny': 74,
 'another': 75,
 'nothing': 76,
 'role': 77,
 'old': 78,
 'new': 79,
 'every': 80,
 'girl': 81,
 'point': 82,
 'cast': 83,
 'world': 84,
 'fact': 85,
 'quite': 86,
 'got': 87,
 'feel': 88,
 'day': 89,
 'pretty': 90,
 'thought': 91,
 'seems': 92,
 'around': 93,
 'minute': 94,
 'young': 95,
 'comedy': 96,
 'horror': 97,
 'enough': 98,
 'big': 99,
 'may': 100,
 'right': 101,
 'action': 102,
 'bit': 103,
 'fan': 104,
 'star': 105,
 'however': 106,
 'friend': 107,
 'without': 108,
 'line': 109,
 'kind': 110,
 'long': 111,
 'saw': 112,
 'original': 113,
 'always': 114,
 'must': 115,
 'music': 116,
 'almost': 117,
 'family': 118,
 'series': 119,
 'whole': 120,
 'least': 121,
 'interesting': 122,
 'set': 123,
 'script': 124,
 'try': 125,
 'done': 126,
 'kid': 127,
 'might': 128,
 'shot': 129,
 'far': 130,
 'last': 131,
 'anything': 132,
 'start': 133,
 'effect': 134,
 'since': 135,
 'probably': 136,
 'reason': 137,
 'put': 138,
 'tv': 139,
 'book': 140,
 'place': 141,
 'away': 142,
 'moment': 143,
 'rather': 144,
 'yet': 145,
 'worst': 146,
 'need': 147,
 'fun': 148,
 'found': 149,
 'let': 150,
 'anyone': 151,
 'sure': 152,
 'played': 153,
 'idea': 154,
 'audience': 155,
 'tell': 156,
 'making': 157,
 'turn': 158,
 'believe': 159,
 'child': 160,
 'trying': 161,
 'dvd': 162,
 'course': 163,
 'american': 164,
 'especially': 165,
 'episode': 166,
 'hard': 167,
 'ending': 168,
 'mean': 169,
 'job': 170,
 'although': 171,
 'war': 172,
 'everything': 173,
 'worth': 174,
 'different': 175,
 'someone': 176,
 'main': 177,
 'looking': 178,
 'screen': 179,
 'keep': 180,
 'watched': 181,
 'maybe': 182,
 'problem': 183,
 'sense': 184,
 'three': 185,
 'version': 186,
 'everyone': 187,
 'money': 188,
 'true': 189,
 'help': 190,
 'night': 191,
 'together': 192,
 'said': 193,
 'seem': 194,
 '10': 195,
 'second': 196,
 'boy': 197,
 '2': 198,
 'special': 199,
 'instead': 200,
 'beautiful': 201,
 'seeing': 202,
 'john': 203,
 'left': 204,
 'later': 205,
 'death': 206,
 'lead': 207,
 'black': 208,
 'wife': 209,
 'excellent': 210,
 'laugh': 211,
 'short': 212,
 'hour': 213,
 'house': 214,
 'sound': 215,
 'mind': 216,
 'classic': 217,
 'name': 218,
 'read': 219,
 'high': 220,
 'viewer': 221,
 'simply': 222,
 'completely': 223,
 'father': 224,
 'used': 225,
 'piece': 226,
 'nice': 227,
 'production': 228,
 'poor': 229,
 'else': 230,
 'face': 231,
 'men': 232,
 'home': 233,
 'along': 234,
 'human': 235,
 'couple': 236,
 'eye': 237,
 'picture': 238,
 'song': 239,
 'word': 240,
 'less': 241,
 'hollywood': 242,
 'use': 243,
 'half': 244,
 'given': 245,
 'enjoy': 246,
 'rest': 247,
 'boring': 248,
 'head': 249,
 'either': 250,
 'truly': 251,
 'camera': 252,
 'school': 253,
 'video': 254,
 'dead': 255,
 'wrong': 256,
 'recommend': 257,
 'hope': 258,
 'kill': 259,
 'stupid': 260,
 'next': 261,
 'came': 262,
 'getting': 263,
 'hand': 264,
 'person': 265,
 'understand': 266,
 'remember': 267,
 'full': 268,
 'sort': 269,
 'game': 270,
 'sex': 271,
 'mr': 272,
 'terrible': 273,
 'dialogue': 274,
 'case': 275,
 'others': 276,
 'awful': 277,
 'run': 278,
 'attempt': 279,
 'budget': 280,
 'wonderful': 281,
 'top': 282,
 'act': 283,
 'fall': 284,
 'mother': 285,
 'playing': 286,
 'perhaps': 287,
 'care': 288,
 'title': 289,
 'sequence': 290,
 'often': 291,
 'flick': 292,
 'perfect': 293,
 'small': 294,
 'joke': 295,
 'definitely': 296,
 'review': 297,
 'early': 298,
 'style': 299,
 'went': 300,
 'absolutely': 301,
 'feeling': 302,
 'example': 303,
 'brother': 304,
 'certainly': 305,
 'become': 306,
 'liked': 307,
 'killer': 308,
 'loved': 309,
 'quality': 310,
 'waste': 311,
 'entire': 312,
 'felt': 313,
 'supposed': 314,
 'actress': 315,
 'cinema': 316,
 'lost': 317,
 'car': 318,
 'drama': 319,
 'several': 320,
 'live': 321,
 'entertaining': 322,
 'lack': 323,
 'art': 324,
 'written': 325,
 'worse': 326,
 'writer': 327,
 'finally': 328,
 'beginning': 329,
 'matter': 330,
 'direction': 331,
 'comment': 332,
 'totally': 333,
 'feature': 334,
 'begin': 335,
 'favorite': 336,
 'son': 337,
 'side': 338,
 'seemed': 339,
 'wanted': 340,
 'yes': 341,
 'based': 342,
 'fight': 343,
 'dark': 344,
 'white': 345,
 'becomes': 346,
 'humor': 347,
 'evil': 348,
 'already': 349,
 'change': 350,
 'guess': 351,
 'final': 352,
 'murder': 353,
 'low': 354,
 'meet': 355,
 '3': 356,
 'called': 357,
 'relationship': 358,
 'able': 359,
 'throughout': 360,
 'hero': 361,
 'oh': 362,
 'number': 363,
 'heart': 364,
 'type': 365,
 'fine': 366,
 'michael': 367,
 'despite': 368,
 'writing': 369,
 'experience': 370,
 '\x96': 371,
 'history': 372,
 'horrible': 373,
 'group': 374,
 'today': 375,
 'amazing': 376,
 'town': 377,
 'call': 378,
 'move': 379,
 'daughter': 380,
 'hit': 381,
 'genre': 382,
 'city': 383,
 'gave': 384,
 'enjoyed': 385,
 'voice': 386,
 'unfortunately': 387,
 'past': 388,
 'cut': 389,
 'talent': 390,
 'power': 391,
 'event': 392,
 'behind': 393,
 'add': 394,
 'save': 395,
 'expect': 396,
 'wonder': 397,
 '1': 398,
 'robert': 399,
 'stuff': 400,
 'theme': 401,
 'god': 402,
 'age': 403,
 'brilliant': 404,
 'credit': 405,
 'stop': 406,
 'situation': 407,
 'chance': 408,
 'obviously': 409,
 'body': 410,
 'sometimes': 411,
 'killed': 412,
 'soon': 413,
 'overall': 414,
 'thinking': 415,
 'score': 416,
 'took': 417,
 'question': 418,
 'directed': 419,
 'decent': 420,
 'late': 421,
 'heard': 422,
 'level': 423,
 'wish': 424,
 'happens': 425,
 'element': 426,
 'highly': 427,
 'close': 428,
 'except': 429,
 'view': 430,
 'extremely': 431,
 'talk': 432,
 'leave': 433,
 'stand': 434,
 'order': 435,
 'blood': 436,
 'told': 437,
 'novel': 438,
 'monster': 439,
 'police': 440,
 'etc': 441,
 'country': 442,
 'coming': 443,
 'looked': 444,
 'career': 445,
 'involved': 446,
 'documentary': 447,
 'strong': 448,
 'particularly': 449,
 'interest': 450,
 'living': 451,
 'including': 452,
 'light': 453,
 'complete': 454,
 'husband': 455,
 'serious': 456,
 'shown': 457,
 'taken': 458,
 'effort': 459,
 'deal': 460,
 'musical': 461,
 'simple': 462,
 'reality': 463,
 'obvious': 464,
 'happened': 465,
 'hilarious': 466,
 'violence': 467,
 'opinion': 468,
 'happen': 469,
 'twist': 470,
 'female': 471,
 'sister': 472,
 'james': 473,
 'david': 474,
 'hell': 475,
 'cool': 476,
 'lady': 477,
 'across': 478,
 'theater': 479,
 'known': 480,
 'exactly': 481,
 'sequel': 482,
 'opening': 483,
 'ago': 484,
 'usually': 485,
 'saying': 486,
 'released': 487,
 'rating': 488,
 'slow': 489,
 'huge': 490,
 'value': 491,
 'room': 492,
 'ok': 493,
 'crap': 494,
 'whose': 495,
 'cinematography': 496,
 'english': 497,
 'local': 498,
 'filmmaker': 499,
 'miss': 500,
 'dialog': 501,
 'major': 502,
 'possible': 503,
 'sad': 504,
 'zombie': 505,
 'alone': 506,
 'none': 507,
 'running': 508,
 'dog': 509,
 'gore': 510,
 'seriously': 511,
 'annoying': 512,
 'started': 513,
 'cop': 514,
 'stay': 515,
 'please': 516,
 'taking': 517,
 'somewhat': 518,
 'usual': 519,
 'knew': 520,
 'ridiculous': 521,
 'message': 522,
 'dream': 523,
 'important': 524,
 'beyond': 525,
 'mostly': 526,
 'turned': 527,
 'open': 528,
 'tale': 529,
 'comic': 530,
 'due': 531,
 'hate': 532,
 'silly': 533,
 'return': 534,
 'thriller': 535,
 'strange': 536,
 'mention': 537,
 'attention': 538,
 'jack': 539,
 'team': 540,
 'scary': 541,
 'surprise': 542,
 '5': 543,
 'apparently': 544,
 'king': 545,
 'anyway': 546,
 'upon': 547,
 'parent': 548,
 'talking': 549,
 'single': 550,
 'figure': 551,
 'street': 552,
 'image': 553,
 'happy': 554,
 'member': 555,
 'producer': 556,
 '80': 557,
 'cheap': 558,
 'clearly': 559,
 'four': 560,
 'television': 561,
 'result': 562,
 'basically': 563,
 '4': 564,
 'subject': 565,
 'george': 566,
 'disappointed': 567,
 'rock': 568,
 'british': 569,
 'state': 570,
 'season': 571,
 'release': 572,
 'modern': 573,
 'hold': 574,
 'soundtrack': 575,
 'doubt': 576,
 'whether': 577,
 'french': 578,
 'appears': 579,
 'predictable': 580,
 'giving': 581,
 'earth': 582,
 'easily': 583,
 'bring': 584,
 'crime': 585,
 'ten': 586,
 'western': 587,
 'form': 588,
 'space': 589,
 'class': 590,
 'supporting': 591,
 'killing': 592,
 'villain': 593,
 'romantic': 594,
 'similar': 595,
 'buy': 596,
 'aspect': 597,
 'viewing': 598,
 'showing': 599,
 'future': 600,
 'entertainment': 601,
 'peter': 602,
 'storyline': 603,
 'bunch': 604,
 'mystery': 605,
 'enjoyable': 606,
 'gun': 607,
 'within': 608,
 'soldier': 609,
 'clear': 610,
 'tried': 611,
 'five': 612,
 'surprised': 613,
 'moving': 614,
 'certain': 615,
 'adult': 616,
 'drug': 617,
 'break': 618,
 'middle': 619,
 'emotion': 620,
 'oscar': 621,
 'among': 622,
 'doctor': 623,
 'filmed': 624,
 'named': 625,
 'dull': 626,
 'working': 627,
 'easy': 628,
 'kept': 629,
 'typical': 630,
 'near': 631,
 'setting': 632,
 'present': 633,
 'using': 634,
 'greatest': 635,
 'gone': 636,
 'general': 637,
 'dance': 638,
 'nearly': 639,
 'force': 640,
 'sorry': 641,
 'actual': 642,
 'student': 643,
 'material': 644,
 'battle': 645,
 'victim': 646,
 'standard': 647,
 'detail': 648,
 'note': 649,
 'straight': 650,
 'suspense': 651,
 'period': 652,
 'brought': 653,
 'fantastic': 654,
 'die': 655,
 'editing': 656,
 'famous': 657,
 'check': 658,
 'cartoon': 659,
 'realistic': 660,
 'premise': 661,
 'animation': 662,
 'imagine': 663,
 'dr': 664,
 'richard': 665,
 'fit': 666,
 'rent': 667,
 'spoiler': 668,
 'hear': 669,
 'issue': 670,
 'copy': 671,
 'somehow': 672,
 'wait': 673,
 'offer': 674,
 'mark': 675,
 'paul': 676,
 'truth': 677,
 'alien': 678,
 'forget': 679,
 'america': 680,
 'learn': 681,
 'york': 682,
 'particular': 683,
 'escape': 684,
 'weak': 685,
 'sit': 686,
 'tom': 687,
 'believable': 688,
 'water': 689,
 'background': 690,
 'romance': 691,
 'leaf': 692,
 'expected': 693,
 'masterpiece': 694,
 'atmosphere': 695,
 'male': 696,
 'red': 697,
 'decided': 698,
 'vampire': 699,
 'eventually': 700,
 'pay': 701,
 'german': 702,
 'avoid': 703,
 'difficult': 704,
 'crew': 705,
 'cover': 706,
 'deep': 707,
 'society': 708,
 'fast': 709,
 'okay': 710,
 'walk': 711,
 'average': 712,
 'studio': 713,
 'baby': 714,
 'became': 715,
 'stage': 716,
 'gay': 717,
 'secret': 718,
 'emotional': 719,
 'possibly': 720,
 'indeed': 721,
 'poorly': 722,
 'de': 723,
 'choice': 724,
 '20': 725,
 'follow': 726,
 'lame': 727,
 'beauty': 728,
 'footage': 729,
 'shame': 730,
 'forced': 731,
 'reading': 732,
 'focus': 733,
 'needed': 734,
 'island': 735,
 'box': 736,
 'screenplay': 737,
 'lee': 738,
 '70': 739,
 'wood': 740,
 'party': 741,
 'whatever': 742,
 'remake': 743,
 'memorable': 744,
 'third': 745,
 'scifi': 746,
 'sexual': 747,
 'write': 748,
 'previous': 749,
 'nature': 750,
 'b': 751,
 'interested': 752,
 'accent': 753,
 'fire': 754,
 'cheesy': 755,
 'week': 756,
 'la': 757,
 'personal': 758,
 'imdb': 759,
 'touch': 760,
 'hot': 761,
 'inside': 762,
 'location': 763,
 'total': 764,
 'superb': 765,
 'unless': 766,
 'otherwise': 767,
 'animal': 768,
 'bill': 769,
 'towards': 770,
 'incredibly': 771,
 'perfectly': 772,
 'weird': 773,
 'plus': 774,
 'adventure': 775,
 'match': 776,
 'plan': 777,
 'air': 778,
 'quickly': 779,
 'development': 780,
 'girlfriend': 781,
 'japanese': 782,
 'realize': 783,
 'crazy': 784,
 'worked': 785,
 'lover': 786,
 'badly': 787,
 'unique': 788,
 'earlier': 789,
 'older': 790,
 'amount': 791,
 'win': 792,
 'front': 793,
 'cry': 794,
 'various': 795,
 'company': 796,
 'free': 797,
 'brings': 798,
 'pick': 799,
 'disney': 800,
 'rich': 801,
 'fear': 802,
 'plenty': 803,
 'appear': 804,
 'business': 805,
 'mess': 806,
 'admit': 807,
 'fairly': 808,
 'master': 809,
 'forward': 810,
 'ask': 811,
 'powerful': 812,
 'costume': 813,
 'term': 814,
 'fantasy': 815,
 'project': 816,
 'spent': 817,
 'following': 818,
 'leading': 819,
 'directing': 820,
 'portrayed': 821,
 'creepy': 822,
 'dramatic': 823,
 'success': 824,
 'acted': 825,
 'band': 826,
 'joe': 827,
 'award': 828,
 'rate': 829,
 'outside': 830,
 'dumb': 831,
 'plain': 832,
 'deserves': 833,
 'memory': 834,
 'meant': 835,
 'portrayal': 836,
 'manages': 837,
 'political': 838,
 'fails': 839,
 'trouble': 840,
 'expecting': 841,
 'italian': 842,
 'wasted': 843,
 'create': 844,
 '30': 845,
 'store': 846,
 'train': 847,
 'caught': 848,
 'brain': 849,
 'agree': 850,
 'spirit': 851,
 'hardly': 852,
 'missing': 853,
 'cat': 854,
 'throw': 855,
 'appearance': 856,
 'fighting': 857,
 '90': 858,
 'ability': 859,
 'chase': 860,
 'recently': 861,
 'creature': 862,
 'apart': 863,
 'large': 864,
 'concept': 865,
 'shoot': 866,
 'william': 867,
 'attack': 868,
 'list': 869,
 'clever': 870,
 'teen': 871,
 'ended': 872,
 'pace': 873,
 'ghost': 874,
 'talented': 875,
 'mistake': 876,
 'channel': 877,
 'telling': 878,
 'cute': 879,
 'laughing': 880,
 'pull': 881,
 'public': 882,
 'stick': 883,
 'pure': 884,
 'potential': 885,
 'color': 886,
 'odd': 887,
 'player': 888,
 'waiting': 889,
 'blue': 890,
 'casting': 891,
 'depth': 892,
 'indian': 893,
 'century': 894,
 'tension': 895,
 'created': 896,
 'missed': 897,
 'us': 898,
 'language': 899,
 'van': 900,
 'visual': 901,
 'married': 902,
 'unlike': 903,
 'era': 904,
 'slightly': 905,
 'soul': 906,
 'incredible': 907,
 'door': 908,
 'familiar': 909,
 'nudity': 910,
 'decides': 911,
 'office': 912,
 'considering': 913,
 'died': 914,
 'hole': 915,
 'scott': 916,
 'answer': 917,
 'extra': 918,
 'speak': 919,
 'entirely': 920,
 'mentioned': 921,
 'popular': 922,
 'flat': 923,
 'control': 924,
 'respect': 925,
 'wrote': 926,
 'catch': 927,
 'appreciate': 928,
 'positive': 929,
 'produced': 930,
 'basic': 931,
 'purpose': 932,
 'drive': 933,
 'critic': 934,
 'bored': 935,
 'compared': 936,
 'maker': 937,
 'neither': 938,
 'convincing': 939,
 'follows': 940,
 'culture': 941,
 'former': 942,
 'gang': 943,
 'younger': 944,
 'suddenly': 945,
 'biggest': 946,
 'college': 947,
 'taste': 948,
 'million': 949,
 'sweet': 950,
 'common': 951,
 'sadly': 952,
 'science': 953,
 'intelligent': 954,
 'track': 955,
 'lie': 956,
 'dancing': 957,
 'carry': 958,
 'hair': 959,
 'violent': 960,
 'adaptation': 961,
 'social': 962,
 'building': 963,
 'belief': 964,
 'meaning': 965,
 'spend': 966,
 'filled': 967,
 'successful': 968,
 'cold': 969,
 'recent': 970,
 'decide': 971,
 'camp': 972,
 'flaw': 973,
 'christmas': 974,
 'mad': 975,
 'fake': 976,
 'genius': 977,
 'bizarre': 978,
 'longer': 979,
 'bother': 980,
 'alive': 981,
 'teenager': 982,
 'tone': 983,
 'ride': 984,
 'shooting': 985,
 'land': 986,
 'computer': 987,
 '50': 988,
 'consider': 989,
 'amusing': 990,
 'road': 991,
 'exciting': 992,
 'park': 993,
 'reviewer': 994,
 'scientist': 995,
 'sick': 996,
 'trip': 997,
 'involving': 998,
 '15': 999,
 'pointless': 1000,
 ...}

In [39]:
word_dic=Tokenizer.word_index       
word_dic

{'<OOV>': 1,
 'movie': 2,
 'film': 3,
 'one': 4,
 'like': 5,
 'would': 6,
 'time': 7,
 'good': 8,
 'character': 9,
 'get': 10,
 'even': 11,
 'story': 12,
 'make': 13,
 'see': 14,
 'really': 15,
 'scene': 16,
 'much': 17,
 'could': 18,
 'well': 19,
 'people': 20,
 'great': 21,
 'bad': 22,
 'also': 23,
 'show': 24,
 'first': 25,
 'way': 26,
 'thing': 27,
 'made': 28,
 'think': 29,
 'life': 30,
 'go': 31,
 'know': 32,
 'watch': 33,
 'love': 34,
 'many': 35,
 'seen': 36,
 'actor': 37,
 'two': 38,
 'plot': 39,
 'say': 40,
 'never': 41,
 'look': 42,
 'acting': 43,
 'end': 44,
 'little': 45,
 'best': 46,
 'year': 47,
 'ever': 48,
 'better': 49,
 'take': 50,
 'man': 51,
 'come': 52,
 'still': 53,
 'work': 54,
 'want': 55,
 'find': 56,
 'part': 57,
 'something': 58,
 'give': 59,
 'lot': 60,
 'cannot': 61,
 'back': 62,
 'u': 63,
 'director': 64,
 'real': 65,
 'guy': 66,
 'watching': 67,
 'performance': 68,
 'play': 69,
 'going': 70,
 'woman': 71,
 'though': 72,
 'actually': 73,
 'funny': 74,
 'another': 75,
 'nothing': 76,
 'role': 77,
 'old': 78,
 'new': 79,
 'every': 80,
 'girl': 81,
 'point': 82,
 'cast': 83,
 'world': 84,
 'fact': 85,
 'quite': 86,
 'got': 87,
 'feel': 88,
 'day': 89,
 'pretty': 90,
 'thought': 91,
 'seems': 92,
 'around': 93,
 'minute': 94,
 'young': 95,
 'comedy': 96,
 'horror': 97,
 'enough': 98,
 'big': 99,
 'may': 100,
 'right': 101,
 'action': 102,
 'bit': 103,
 'fan': 104,
 'star': 105,
 'however': 106,
 'friend': 107,
 'without': 108,
 'line': 109,
 'kind': 110,
 'long': 111,
 'saw': 112,
 'original': 113,
 'always': 114,
 'must': 115,
 'music': 116,
 'almost': 117,
 'family': 118,
 'series': 119,
 'whole': 120,
 'least': 121,
 'interesting': 122,
 'set': 123,
 'script': 124,
 'try': 125,
 'done': 126,
 'kid': 127,
 'might': 128,
 'shot': 129,
 'far': 130,
 'last': 131,
 'anything': 132,
 'start': 133,
 'effect': 134,
 'since': 135,
 'probably': 136,
 'reason': 137,
 'put': 138,
 'tv': 139,
 'book': 140,
 'place': 141,
 'away': 142,
 'moment': 143,
 'rather': 144,
 'yet': 145,
 'worst': 146,
 'need': 147,
 'fun': 148,
 'found': 149,
 'let': 150,
 'anyone': 151,
 'sure': 152,
 'played': 153,
 'idea': 154,
 'audience': 155,
 'tell': 156,
 'making': 157,
 'turn': 158,
 'believe': 159,
 'child': 160,
 'trying': 161,
 'dvd': 162,
 'course': 163,
 'american': 164,
 'especially': 165,
 'episode': 166,
 'hard': 167,
 'ending': 168,
 'mean': 169,
 'job': 170,
 'although': 171,
 'war': 172,
 'everything': 173,
 'worth': 174,
 'different': 175,
 'someone': 176,
 'main': 177,
 'looking': 178,
 'screen': 179,
 'keep': 180,
 'watched': 181,
 'maybe': 182,
 'problem': 183,
 'sense': 184,
 'three': 185,
 'version': 186,
 'everyone': 187,
 'money': 188,
 'true': 189,
 'help': 190,
 'night': 191,
 'together': 192,
 'said': 193,
 'seem': 194,
 '10': 195,
 'second': 196,
 'boy': 197,
 '2': 198,
 'special': 199,
 'instead': 200,
 'beautiful': 201,
 'seeing': 202,
 'john': 203,
 'left': 204,
 'later': 205,
 'death': 206,
 'lead': 207,
 'black': 208,
 'wife': 209,
 'excellent': 210,
 'laugh': 211,
 'short': 212,
 'hour': 213,
 'house': 214,
 'sound': 215,
 'mind': 216,
 'classic': 217,
 'name': 218,
 'read': 219,
 'high': 220,
 'viewer': 221,
 'simply': 222,
 'completely': 223,
 'father': 224,
 'used': 225,
 'piece': 226,
 'nice': 227,
 'production': 228,
 'poor': 229,
 'else': 230,
 'face': 231,
 'men': 232,
 'home': 233,
 'along': 234,
 'human': 235,
 'couple': 236,
 'eye': 237,
 'picture': 238,
 'song': 239,
 'word': 240,
 'less': 241,
 'hollywood': 242,
 'use': 243,
 'half': 244,
 'given': 245,
 'enjoy': 246,
 'rest': 247,
 'boring': 248,
 'head': 249,
 'either': 250,
 'truly': 251,
 'camera': 252,
 'school': 253,
 'video': 254,
 'dead': 255,
 'wrong': 256,
 'recommend': 257,
 'hope': 258,
 'kill': 259,
 'stupid': 260,
 'next': 261,
 'came': 262,
 'getting': 263,
 'hand': 264,
 'person': 265,
 'understand': 266,
 'remember': 267,
 'full': 268,
 'sort': 269,
 'game': 270,
 'sex': 271,
 'mr': 272,
 'terrible': 273,
 'dialogue': 274,
 'case': 275,
 'others': 276,
 'awful': 277,
 'run': 278,
 'attempt': 279,
 'budget': 280,
 'wonderful': 281,
 'top': 282,
 'act': 283,
 'fall': 284,
 'mother': 285,
 'playing': 286,
 'perhaps': 287,
 'care': 288,
 'title': 289,
 'sequence': 290,
 'often': 291,
 'flick': 292,
 'perfect': 293,
 'small': 294,
 'joke': 295,
 'definitely': 296,
 'review': 297,
 'early': 298,
 'style': 299,
 'went': 300,
 'absolutely': 301,
 'feeling': 302,
 'example': 303,
 'brother': 304,
 'certainly': 305,
 'become': 306,
 'liked': 307,
 'killer': 308,
 'loved': 309,
 'quality': 310,
 'waste': 311,
 'entire': 312,
 'felt': 313,
 'supposed': 314,
 'actress': 315,
 'cinema': 316,
 'lost': 317,
 'car': 318,
 'drama': 319,
 'several': 320,
 'live': 321,
 'entertaining': 322,
 'lack': 323,
 'art': 324,
 'written': 325,
 'worse': 326,
 'writer': 327,
 'finally': 328,
 'beginning': 329,
 'matter': 330,
 'direction': 331,
 'comment': 332,
 'totally': 333,
 'feature': 334,
 'begin': 335,
 'favorite': 336,
 'son': 337,
 'side': 338,
 'seemed': 339,
 'wanted': 340,
 'yes': 341,
 'based': 342,
 'fight': 343,
 'dark': 344,
 'white': 345,
 'becomes': 346,
 'humor': 347,
 'evil': 348,
 'already': 349,
 'change': 350,
 'guess': 351,
 'final': 352,
 'murder': 353,
 'low': 354,
 'meet': 355,
 '3': 356,
 'called': 357,
 'relationship': 358,
 'able': 359,
 'throughout': 360,
 'hero': 361,
 'oh': 362,
 'number': 363,
 'heart': 364,
 'type': 365,
 'fine': 366,
 'michael': 367,
 'despite': 368,
 'writing': 369,
 'experience': 370,
 '\x96': 371,
 'history': 372,
 'horrible': 373,
 'group': 374,
 'today': 375,
 'amazing': 376,
 'town': 377,
 'call': 378,
 'move': 379,
 'daughter': 380,
 'hit': 381,
 'genre': 382,
 'city': 383,
 'gave': 384,
 'enjoyed': 385,
 'voice': 386,
 'unfortunately': 387,
 'past': 388,
 'cut': 389,
 'talent': 390,
 'power': 391,
 'event': 392,
 'behind': 393,
 'add': 394,
 'save': 395,
 'expect': 396,
 'wonder': 397,
 '1': 398,
 'robert': 399,
 'stuff': 400,
 'theme': 401,
 'god': 402,
 'age': 403,
 'brilliant': 404,
 'credit': 405,
 'stop': 406,
 'situation': 407,
 'chance': 408,
 'obviously': 409,
 'body': 410,
 'sometimes': 411,
 'killed': 412,
 'soon': 413,
 'overall': 414,
 'thinking': 415,
 'score': 416,
 'took': 417,
 'question': 418,
 'directed': 419,
 'decent': 420,
 'late': 421,
 'heard': 422,
 'level': 423,
 'wish': 424,
 'happens': 425,
 'element': 426,
 'highly': 427,
 'close': 428,
 'except': 429,
 'view': 430,
 'extremely': 431,
 'talk': 432,
 'leave': 433,
 'stand': 434,
 'order': 435,
 'blood': 436,
 'told': 437,
 'novel': 438,
 'monster': 439,
 'police': 440,
 'etc': 441,
 'country': 442,
 'coming': 443,
 'looked': 444,
 'career': 445,
 'involved': 446,
 'documentary': 447,
 'strong': 448,
 'particularly': 449,
 'interest': 450,
 'living': 451,
 'including': 452,
 'light': 453,
 'complete': 454,
 'husband': 455,
 'serious': 456,
 'shown': 457,
 'taken': 458,
 'effort': 459,
 'deal': 460,
 'musical': 461,
 'simple': 462,
 'reality': 463,
 'obvious': 464,
 'happened': 465,
 'hilarious': 466,
 'violence': 467,
 'opinion': 468,
 'happen': 469,
 'twist': 470,
 'female': 471,
 'sister': 472,
 'james': 473,
 'david': 474,
 'hell': 475,
 'cool': 476,
 'lady': 477,
 'across': 478,
 'theater': 479,
 'known': 480,
 'exactly': 481,
 'sequel': 482,
 'opening': 483,
 'ago': 484,
 'usually': 485,
 'saying': 486,
 'released': 487,
 'rating': 488,
 'slow': 489,
 'huge': 490,
 'value': 491,
 'room': 492,
 'ok': 493,
 'crap': 494,
 'whose': 495,
 'cinematography': 496,
 'english': 497,
 'local': 498,
 'filmmaker': 499,
 'miss': 500,
 'dialog': 501,
 'major': 502,
 'possible': 503,
 'sad': 504,
 'zombie': 505,
 'alone': 506,
 'none': 507,
 'running': 508,
 'dog': 509,
 'gore': 510,
 'seriously': 511,
 'annoying': 512,
 'started': 513,
 'cop': 514,
 'stay': 515,
 'please': 516,
 'taking': 517,
 'somewhat': 518,
 'usual': 519,
 'knew': 520,
 'ridiculous': 521,
 'message': 522,
 'dream': 523,
 'important': 524,
 'beyond': 525,
 'mostly': 526,
 'turned': 527,
 'open': 528,
 'tale': 529,
 'comic': 530,
 'due': 531,
 'hate': 532,
 'silly': 533,
 'return': 534,
 'thriller': 535,
 'strange': 536,
 'mention': 537,
 'attention': 538,
 'jack': 539,
 'team': 540,
 'scary': 541,
 'surprise': 542,
 '5': 543,
 'apparently': 544,
 'king': 545,
 'anyway': 546,
 'upon': 547,
 'parent': 548,
 'talking': 549,
 'single': 550,
 'figure': 551,
 'street': 552,
 'image': 553,
 'happy': 554,
 'member': 555,
 'producer': 556,
 '80': 557,
 'cheap': 558,
 'clearly': 559,
 'four': 560,
 'television': 561,
 'result': 562,
 'basically': 563,
 '4': 564,
 'subject': 565,
 'george': 566,
 'disappointed': 567,
 'rock': 568,
 'british': 569,
 'state': 570,
 'season': 571,
 'release': 572,
 'modern': 573,
 'hold': 574,
 'soundtrack': 575,
 'doubt': 576,
 'whether': 577,
 'french': 578,
 'appears': 579,
 'predictable': 580,
 'giving': 581,
 'earth': 582,
 'easily': 583,
 'bring': 584,
 'crime': 585,
 'ten': 586,
 'western': 587,
 'form': 588,
 'space': 589,
 'class': 590,
 'supporting': 591,
 'killing': 592,
 'villain': 593,
 'romantic': 594,
 'similar': 595,
 'buy': 596,
 'aspect': 597,
 'viewing': 598,
 'showing': 599,
 'future': 600,
 'entertainment': 601,
 'peter': 602,
 'storyline': 603,
 'bunch': 604,
 'mystery': 605,
 'enjoyable': 606,
 'gun': 607,
 'within': 608,
 'soldier': 609,
 'clear': 610,
 'tried': 611,
 'five': 612,
 'surprised': 613,
 'moving': 614,
 'certain': 615,
 'adult': 616,
 'drug': 617,
 'break': 618,
 'middle': 619,
 'emotion': 620,
 'oscar': 621,
 'among': 622,
 'doctor': 623,
 'filmed': 624,
 'named': 625,
 'dull': 626,
 'working': 627,
 'easy': 628,
 'kept': 629,
 'typical': 630,
 'near': 631,
 'setting': 632,
 'present': 633,
 'using': 634,
 'greatest': 635,
 'gone': 636,
 'general': 637,
 'dance': 638,
 'nearly': 639,
 'force': 640,
 'sorry': 641,
 'actual': 642,
 'student': 643,
 'material': 644,
 'battle': 645,
 'victim': 646,
 'standard': 647,
 'detail': 648,
 'note': 649,
 'straight': 650,
 'suspense': 651,
 'period': 652,
 'brought': 653,
 'fantastic': 654,
 'die': 655,
 'editing': 656,
 'famous': 657,
 'check': 658,
 'cartoon': 659,
 'realistic': 660,
 'premise': 661,
 'animation': 662,
 'imagine': 663,
 'dr': 664,
 'richard': 665,
 'fit': 666,
 'rent': 667,
 'spoiler': 668,
 'hear': 669,
 'issue': 670,
 'copy': 671,
 'somehow': 672,
 'wait': 673,
 'offer': 674,
 'mark': 675,
 'paul': 676,
 'truth': 677,
 'alien': 678,
 'forget': 679,
 'america': 680,
 'learn': 681,
 'york': 682,
 'particular': 683,
 'escape': 684,
 'weak': 685,
 'sit': 686,
 'tom': 687,
 'believable': 688,
 'water': 689,
 'background': 690,
 'romance': 691,
 'leaf': 692,
 'expected': 693,
 'masterpiece': 694,
 'atmosphere': 695,
 'male': 696,
 'red': 697,
 'decided': 698,
 'vampire': 699,
 'eventually': 700,
 'pay': 701,
 'german': 702,
 'avoid': 703,
 'difficult': 704,
 'crew': 705,
 'cover': 706,
 'deep': 707,
 'society': 708,
 'fast': 709,
 'okay': 710,
 'walk': 711,
 'average': 712,
 'studio': 713,
 'baby': 714,
 'became': 715,
 'stage': 716,
 'gay': 717,
 'secret': 718,
 'emotional': 719,
 'possibly': 720,
 'indeed': 721,
 'poorly': 722,
 'de': 723,
 'choice': 724,
 '20': 725,
 'follow': 726,
 'lame': 727,
 'beauty': 728,
 'footage': 729,
 'shame': 730,
 'forced': 731,
 'reading': 732,
 'focus': 733,
 'needed': 734,
 'island': 735,
 'box': 736,
 'screenplay': 737,
 'lee': 738,
 '70': 739,
 'wood': 740,
 'party': 741,
 'whatever': 742,
 'remake': 743,
 'memorable': 744,
 'third': 745,
 'scifi': 746,
 'sexual': 747,
 'write': 748,
 'previous': 749,
 'nature': 750,
 'b': 751,
 'interested': 752,
 'accent': 753,
 'fire': 754,
 'cheesy': 755,
 'week': 756,
 'la': 757,
 'personal': 758,
 'imdb': 759,
 'touch': 760,
 'hot': 761,
 'inside': 762,
 'location': 763,
 'total': 764,
 'superb': 765,
 'unless': 766,
 'otherwise': 767,
 'animal': 768,
 'bill': 769,
 'towards': 770,
 'incredibly': 771,
 'perfectly': 772,
 'weird': 773,
 'plus': 774,
 'adventure': 775,
 'match': 776,
 'plan': 777,
 'air': 778,
 'quickly': 779,
 'development': 780,
 'girlfriend': 781,
 'japanese': 782,
 'realize': 783,
 'crazy': 784,
 'worked': 785,
 'lover': 786,
 'badly': 787,
 'unique': 788,
 'earlier': 789,
 'older': 790,
 'amount': 791,
 'win': 792,
 'front': 793,
 'cry': 794,
 'various': 795,
 'company': 796,
 'free': 797,
 'brings': 798,
 'pick': 799,
 'disney': 800,
 'rich': 801,
 'fear': 802,
 'plenty': 803,
 'appear': 804,
 'business': 805,
 'mess': 806,
 'admit': 807,
 'fairly': 808,
 'master': 809,
 'forward': 810,
 'ask': 811,
 'powerful': 812,
 'costume': 813,
 'term': 814,
 'fantasy': 815,
 'project': 816,
 'spent': 817,
 'following': 818,
 'leading': 819,
 'directing': 820,
 'portrayed': 821,
 'creepy': 822,
 'dramatic': 823,
 'success': 824,
 'acted': 825,
 'band': 826,
 'joe': 827,
 'award': 828,
 'rate': 829,
 'outside': 830,
 'dumb': 831,
 'plain': 832,
 'deserves': 833,
 'memory': 834,
 'meant': 835,
 'portrayal': 836,
 'manages': 837,
 'political': 838,
 'fails': 839,
 'trouble': 840,
 'expecting': 841,
 'italian': 842,
 'wasted': 843,
 'create': 844,
 '30': 845,
 'store': 846,
 'train': 847,
 'caught': 848,
 'brain': 849,
 'agree': 850,
 'spirit': 851,
 'hardly': 852,
 'missing': 853,
 'cat': 854,
 'throw': 855,
 'appearance': 856,
 'fighting': 857,
 '90': 858,
 'ability': 859,
 'chase': 860,
 'recently': 861,
 'creature': 862,
 'apart': 863,
 'large': 864,
 'concept': 865,
 'shoot': 866,
 'william': 867,
 'attack': 868,
 'list': 869,
 'clever': 870,
 'teen': 871,
 'ended': 872,
 'pace': 873,
 'ghost': 874,
 'talented': 875,
 'mistake': 876,
 'channel': 877,
 'telling': 878,
 'cute': 879,
 'laughing': 880,
 'pull': 881,
 'public': 882,
 'stick': 883,
 'pure': 884,
 'potential': 885,
 'color': 886,
 'odd': 887,
 'player': 888,
 'waiting': 889,
 'blue': 890,
 'casting': 891,
 'depth': 892,
 'indian': 893,
 'century': 894,
 'tension': 895,
 'created': 896,
 'missed': 897,
 'us': 898,
 'language': 899,
 'van': 900,
 'visual': 901,
 'married': 902,
 'unlike': 903,
 'era': 904,
 'slightly': 905,
 'soul': 906,
 'incredible': 907,
 'door': 908,
 'familiar': 909,
 'nudity': 910,
 'decides': 911,
 'office': 912,
 'considering': 913,
 'died': 914,
 'hole': 915,
 'scott': 916,
 'answer': 917,
 'extra': 918,
 'speak': 919,
 'entirely': 920,
 'mentioned': 921,
 'popular': 922,
 'flat': 923,
 'control': 924,
 'respect': 925,
 'wrote': 926,
 'catch': 927,
 'appreciate': 928,
 'positive': 929,
 'produced': 930,
 'basic': 931,
 'purpose': 932,
 'drive': 933,
 'critic': 934,
 'bored': 935,
 'compared': 936,
 'maker': 937,
 'neither': 938,
 'convincing': 939,
 'follows': 940,
 'culture': 941,
 'former': 942,
 'gang': 943,
 'younger': 944,
 'suddenly': 945,
 'biggest': 946,
 'college': 947,
 'taste': 948,
 'million': 949,
 'sweet': 950,
 'common': 951,
 'sadly': 952,
 'science': 953,
 'intelligent': 954,
 'track': 955,
 'lie': 956,
 'dancing': 957,
 'carry': 958,
 'hair': 959,
 'violent': 960,
 'adaptation': 961,
 'social': 962,
 'building': 963,
 'belief': 964,
 'meaning': 965,
 'spend': 966,
 'filled': 967,
 'successful': 968,
 'cold': 969,
 'recent': 970,
 'decide': 971,
 'camp': 972,
 'flaw': 973,
 'christmas': 974,
 'mad': 975,
 'fake': 976,
 'genius': 977,
 'bizarre': 978,
 'longer': 979,
 'bother': 980,
 'alive': 981,
 'teenager': 982,
 'tone': 983,
 'ride': 984,
 'shooting': 985,
 'land': 986,
 'computer': 987,
 '50': 988,
 'consider': 989,
 'amusing': 990,
 'road': 991,
 'exciting': 992,
 'park': 993,
 'reviewer': 994,
 'scientist': 995,
 'sick': 996,
 'trip': 997,
 'involving': 998,
 '15': 999,
 'pointless': 1000,
 ...}

In [40]:
len(word_dic)

209770

Example what word_dic does

\ **********

In [41]:
"little boy jake think"

'little boy jake think'

In [42]:
word_dic["little"] ,word_dic["boy"],word_dic["jake"],word_dic["think"]

(45, 197, 3315, 29)

In [43]:
Tokenizer.texts_to_sequences(["little boy jake think"])

[[45, 197, 3315, 29]]

**************/

In [44]:
Tokenizer.texts_to_sequences(dfmovie["review"])

[[4,
  994,
  921,
  67,
  398,
  3080,
  166,
  2878,
  101,
  481,
  465,
  6821,
  25,
  27,
  2952,
  3080,
  4936,
  1,
  16,
  467,
  123,
  101,
  240,
  31,
  1544,
  24,
  6245,
  5182,
  1,
  24,
  881,
  1996,
  2029,
  617,
  271,
  467,
  3098,
  217,
  243,
  1,
  357,
  3080,
  8966,
  245,
  1,
  6197,
  2331,
  570,
  1,
  733,
  1221,
  1,
  383,
  4266,
  1926,
  1018,
  1927,
  1795,
  793,
  231,
  1,
  1,
  220,
  4069,
  383,
  233,
  1,
  3756,
  1,
  6646,
  1163,
  842,
  2238,
  1,
  1,
  206,
  3796,
  6647,
  1623,
  7692,
  7370,
  41,
  130,
  1,
  6,
  40,
  177,
  1036,
  24,
  531,
  85,
  31,
  24,
  6,
  2382,
  679,
  90,
  238,
  3885,
  2275,
  155,
  679,
  1112,
  679,
  1,
  806,
  93,
  25,
  166,
  48,
  112,
  2952,
  1422,
  1997,
  18,
  40,
  1393,
  181,
  1309,
  948,
  3080,
  87,
  9080,
  220,
  423,
  1229,
  467,
  467,
  5866,
  6338,
  1898,
  2673,
  1,
  4844,
  259,
  435,
  10,
  142,
  19,
  8763,
  619,
  590,
  4844,
  527,
  1018,
  5013,
  531,
  323,
  552,
  1146,
  1018,
  370,
  67,
  3080,
  100,
  306,
  3404,
  2962,
  1,
  10,
  760,
  3626,
  338],
 [281,
  45,
  228,
  1209,
  1583,
  1,
  1,
  1326,
  59,
  1,
  411,
  1,
  184,
  1717,
  312,
  226,
  37,
  431,
  19,
  2059,
  367,
  3797,
  87,
  1,
  386,
  2933,
  251,
  14,
  1,
  656,
  9081,
  1089,
  1495,
  5395,
  2081,
  19,
  174,
  67,
  1,
  325,
  2145,
  226,
  3902,
  228,
  4,
  21,
  809,
  96,
  30,
  1717,
  15,
  52,
  233,
  45,
  27,
  815,
  1898,
  144,
  243,
  1917,
  523,
  1583,
  1101,
  1005,
  4535,
  69,
  1625,
  4119,
  449,
  16,
  3278,
  1,
  1,
  123,
  449,
  923,
  1,
  1,
  1,
  80,
  1976,
  1726,
  19,
  126],
 [91,
  281,
  26,
  966,
  7,
  761,
  1273,
  2178,
  1050,
  778,
  1,
  479,
  67,
  3615,
  96,
  39,
  3645,
  274,
  1694,
  9,
  1315,
  11,
  19,
  5867,
  5945,
  1235,
  308,
  100,
  567,
  783,
  776,
  82,
  198,
  2260,
  4288,
  91,
  2662,
  2682,
  1612,
  53,
  1223,
  924,
  299,
  35,
  63,
  2100,
  1,
  6,
  1237,
  4,
  1,
  96,
  47,
  2382,
  40,
  1170,
  41,
  1319,
  7554,
  1,
  1132,
  983,
  1097,
  553,
  4518,
  101,
  712,
  4580,
  95,
  1,
  100,
  6545,
  3717,
  445,
  1,
  1593,
  1358,
  1,
  122,
  2294,
  21,
  96,
  31,
  14,
  107],
 [563,
  118,
  45,
  197,
  3315,
  29,
  505,
  3627,
  548,
  857,
  1,
  2,
  7238,
  1642,
  1142,
  945,
  3315,
  911,
  306,
  5396,
  259,
  1,
  25,
  70,
  13,
  3,
  115,
  971,
  535,
  319,
  319,
  2,
  1556,
  548,
  1,
  6069,
  5,
  65,
  30,
  3315,
  3627,
  333,
  1620,
  3,
  693,
  14,
  1,
  595,
  2,
  200,
  181,
  319,
  3477,
  535,
  1,
  195,
  19,
  286,
  548,
  4135,
  501,
  129,
  3315,
  2483],
 [1,
  1,
  34,
  7,
  188,
  1939,
  1222,
  3,
  33,
  272,
  1,
  674,
  63,
  3777,
  2654,
  235,
  2383,
  2,
  92,
  878,
  63,
  188,
  391,
  824,
  20,
  175,
  407,
  1442,
  4581,
  1581,
  1,
  69,
  401,
  64,
  3836,
  102,
  633,
  7,
  79,
  682,
  175,
  9,
  355,
  3364,
  4,
  2953,
  4,
  26,
  75,
  261,
  265,
  4,
  92,
  32,
  749,
  82,
  2338,
  1,
  3,
  3054,
  1,
  42,
  458,
  14,
  20,
  321,
  84,
  321,
  1,
  27,
  4,
  10,
  906,
  238,
  175,
  716,
  4332,
  4,
  1,
  99,
  383,
  481,
  46,
  141,
  235,
  2383,
  56,
  4020,
  1,
  4,
  1,
  275,
  20,
  1,
  43,
  8,
  272,
  1,
  331,
  1183,
  1,
  8127,
  4497,
  3208,
  2551,
  367,
  1,
  6339,
  1,
  247,
  875,
  83,
  13,
  9,
  52,
  1,
  424,
  272,
  1,
  8,
  1891,
  1,
  1,
  261,
  54],
 [136,
  3418,
  336,
  2,
  12,
  1,
  2863,
  6937,
  3099,
  4955,
  248,
  41,
  10,
  78,
  368,
  36,
  999,
  7,
  131,
  2292,
  47,
  676,
  8476,
  68,
  798,
  1174,
  237,
  3729,
  1709,
  4,
  251,
  1955,
  77,
  2443,
  127,
  5712,
  40,
  5,
  1,
  6648,
  160,
  13,
  148,
  33,
  285,
  489,
  6822,
  1194,
  84,
  4333,
  688,
  5463,
  1631,
  2711,
  6,
  2],
 [152,
  6,
  5,
  14,
  7693,
  1806,
  1,
  119,
  6874,
  375,
  6,
  584,
  62,
  127,
  2179,
  6198,
  1862,
  208,
  345,
  139,
  1,
  1,
  361,
  80,
  1,
  1531,
  5183,
  79,
  1378,
  1,
  147,
  350,
  873,
  139,
  6,
  54,
  84,
  689,
  1,
  26,
  1240,
  1,
  5,
  430,
  35,
  4956,
  139,
  35,
  1,
  1,
  26,
  159,
  87,
  55,
  1,
  227,
  219,
  774,
  82,
  1378,
  1,
  6070,
  6,
  195,
  109,
  6,
  150,
  1,
  433,
  576,
  1,
  115,
  31,
  150,
  63],
 [24,
  376,
  1268,
  3665,
  154,
  739,
  25,
  2822,
  25,
  1090,
  1093,
  47,
  404,
  27,
  3055,
  4753,
  24,
  15,
  74,
  1445,
  3348,
  5043,
  454,
  311,
  7,
  1,
  251,
  1,
  130,
  24,
  2683,
  369,
  2079,
  22,
  68,
  117,
  22,
  2356,
  322,
  1,
  1,
  24,
  136,
  6,
  53,
  778,
  56,
  167,
  159,
  2127,
  1,
  113,
  83,
  23,
  2198,
  826,
  3646,
  1352,
  4,
  2114,
  3291,
  14,
  666,
  4536,
  6071,
  313,
  115,
  59,
  198,
  105,
  925,
  113,
  83,
  28,
  24,
  490,
  824,
  24,
  277,
  61,
  159,
  53,
  778],
 [7489,
  929,
  332,
  3,
  178,
  810,
  67,
  3,
  22,
  876,
  36,
  1,
  3,
  251,
  4,
  146,
  277,
  117,
  80,
  26,
  656,
  1589,
  603,
  43,
  575,
  3,
  239,
  727,
  442,
  1718,
  153,
  241,
  560,
  7,
  3,
  42,
  558,
  1422,
  248,
  1233,
  1496,
  554,
  14,
  44,
  405,
  3,
  27,
  8655,
  581,
  1,
  3950,
  8967,
  130,
  46,
  68,
  121,
  92,
  157,
  103,
  459,
  4,
  8967,
  6031],
 [5, 113, 2362, 8128, 1968, 5, 2, 95, 78, 34, 2, 475, 11, 1255, 307, 1, 972],
 [4021,
  678,
  4,
  2357,
  3,
  1029,
  342,
  93,
  1,
  173,
  144,
  642,
  1,
  25,
  887,
  90,
  74,
  2,
  6823,
  56,
  295,
  1,
  74,
  1,
  354,
  280,
  3,
  41,
  183,
  90,
  122,
  9,
  700,
  317,
  1,
  663,
  3,
  6,
  1036,
  6938,
  3292,
  1,
  58,
  595,
  49,
  125,
  304,
  75,
  1054],
 [112,
  2,
  1001,
  262,
  1688,
  5670,
  16,
  99,
  2011,
  1899,
  232,
  1,
  1,
  1,
  101,
  778,
  97,
  1,
  95,
  127,
  70,
  755,
  751,
  3,
  2108,
  2449,
  53,
  1227,
  1826,
  439,
  365,
  2,
  485,
  1712,
  361,
  201,
  71,
  128,
  380,
  1961,
  554,
  3233,
  439,
  914,
  44,
  288,
  17,
  594,
  1253,
  1001,
  47,
  78,
  580,
  39,
  34,
  3676,
  1,
  47,
  205,
  112,
  2021,
  262,
  309,
  105,
  5783,
  4120,
  1,
  298,
  3,
  1541,
  417,
  1113,
  82,
  135,
  2013,
  157,
  12,
  13,
  541,
  503,
  1,
  1826,
  1156],
 [99,
  104,
  3595,
  54,
  35,
  385,
  2,
  1,
  182,
  4,
  3595,
  544,
  1034,
  101,
  243,
  130,
  794,
  111,
  484,
  11,
  270,
  11,
  1,
  20,
  385,
  592,
  1,
  1,
  718,
  1983,
  3234,
  4900,
  8656,
  735,
  2527,
  130,
  794,
  58,
  272,
  3595,
  1,
  192,
  234,
  7239,
  1,
  302,
  1,
  123,
  272,
  3595,
  3438,
  185,
  1,
  69,
  888,
  31,
  218,
  7694,
  1,
  1,
  1,
  1,
  1,
  218,
  73,
  28,
  1134,
  90,
  99,
  2,
  1,
  529,
  31,
  5,
  539,
  1,
  153,
  7694,
  1,
  341,
  1,
  702,
  7855,
  1,
  1899,
  1989,
  106,
  56,
  1,
  43,
  2,
  90,
  8477,
  20,
  6395,
  15,
  3452,
  189,
  120,
  1,
  4069,
  112,
  1,
  25,
  265,
  1682,
  15,
  32,
  444,
  5,
  4498,
  106,
  603,
  3,
  525,
  4869,
  14,
  348,
  975,
  995,
  664,
  1,
  153,
  1,
  1,
  157,
  1,
  1,
  357,
  3100,
  1,
  1983,
  735,
  1538,
  668,
  1,
  137,
  101,
  6291,
  1705,
  200,
  87,
  227,
  801,
  1,
  11,
  636,
  130,
  513,
  794,
  1,
  61,
  31,
  55,
  515,
  189,
  3595,
  8478,
  31,
  14,
  2,
  567,
  1320,
  189,
  3595,
  370,
  965,
  1,
  27,
  174,
  3903,
  6,
  7781,
  3595,
  8,
  54,
  1063,
  3,
  227,
  1484,
  857,
  16,
  120,
  1,
  1,
  3705,
  3270,
  16,
  173,
  13,
  211,
  2,
  130,
  794,
  7555,
  1,
  1,
  1,
  130,
  55,
  50,
  1,
  31,
  1316,
  26,
  1,
  10,
  512,
  3005,
  13,
  55,
  866,
  25,
  185,
  94,
  179],
 [83,
  153,
  1,
  1,
  928,
  161,
  584,
  1551,
  2080,
  1620,
  58,
  1,
  4308,
  69,
  336,
  1551,
  32,
  32,
  615,
  1,
  1,
  2603,
  1,
  611,
  58,
  595,
  5397,
  1,
  240,
  61,
  3886,
  1,
  748,
  748,
  121,
  586,
  109,
  2644,
  497,
  4433,
  41,
  1,
  180,
  70,
  40,
  2,
  486,
  31,
  389],
 [654,
  2,
  185,
  1950,
  306,
  657,
  4,
  37,
  566,
  5784,
  104,
  1488,
  22,
  75,
  8,
  27,
  2,
  575,
  51,
  1632,
  6439,
  1,
  2,
  1202,
  9615,
  7001],
 [110,
  1379,
  2434,
  16,
  783,
  4,
  2096,
  1211,
  103,
  3,
  48,
  36,
  269,
  5,
  220,
  253,
  3,
  816,
  1,
  6788,
  415,
  1585,
  9,
  978,
  314,
  1,
  377,
  90,
  167,
  10,
  446,
  4,
  1205,
  1617,
  404,
  1859,
  3971,
  86,
  521,
  60,
  2082,
  3209,
  1,
  1,
  9500,
  358,
  1107,
  8872,
  1442,
  1678,
  638,
  1202,
  286,
  6546,
  77,
  59,
  4,
  1176,
  5,
  949,
  1292,
  22,
  843,
  3,
  188,
  18,
  817,
  8657,
  160,
  2494,
  2302],
 [3,
  222,
  4845,
  4,
  22,
  3,
  839,
  1019,
  5836,
  1928,
  8129,
  3,
  289,
  8024,
  1,
  210,
  114,
  83,
  574,
  1102,
  3044,
  2074,
  584,
  101,
  88,
  9,
  2416,
  502,
  1447,
  186,
  1,
  130,
  3972,
  1380,
  12,
  279,
  1,
  317,
  1998,
  789,
  3,
  2985,
  1,
  199,
  134,
  40,
  22,
  3,
  246,
  1,
  1928,
  790,
  186,
  17],
 [2,
  28,
  4,
  282,
  195,
  277,
  2,
  373,
  7556,
  94,
  343,
  4,
  439,
  75,
  408,
  9,
  780,
  2924,
  508,
  4,
  2321,
  343,
  75,
  719,
  8658,
  429,
  99,
  22,
  1139,
  340,
  1916,
  16,
  5275,
  2308,
  2,
  1,
  105,
  172,
  2737,
  1,
  874,
  16,
  44,
  2308,
  352,
  16,
  78,
  105,
  172,
  1,
  1,
  4,
  7371,
  4631,
  1139,
  329,
  481,
  5,
  1,
  2663,
  4631,
  534,
  545,
  7782,
  740,
  646,
  3,
  1,
  1,
  8479,
  646,
  4037,
  1,
  1,
  120,
  1139,
  1150,
  235,
  401,
  1,
  1,
  303,
  311,
  7,
  176,
  156,
  1604,
  1604,
  3453,
  12,
  109,
  3020,
  3453,
  1052,
  2,
  18,
  971,
  2184,
  2,
  616,
  2,
  17,
  250,
  277,
  65,
  1206,
  40,
  121,
  395,
  188],
 [267,
  5785,
  25,
  3,
  181,
  316,
  238,
  344,
  141,
  4009,
  62,
  1,
  1060,
  417,
  304,
  472,
  1,
  316,
  1,
  1,
  1707,
  1688,
  3973,
  60,
  2757,
  3,
  23,
  856,
  1,
  1331,
  37,
  2014,
  1,
  29,
  4,
  3973,
  10,
  129,
  1327,
  151,
  32,
  56,
  162,
  441,
  516,
  150,
  1,
  316,
  527,
  1,
  1108,
  99,
  730,
  6939,
  316,
  725,
  1292,
  142,
  6,
  34,
  669,
  276,
  36,
  3,
  5],
 [277,
  3,
  115,
  65,
  3306,
  2137,
  1626,
  4920,
  458,
  12,
  25,
  657,
  471,
  6824,
  4921,
  1,
  525,
  3565,
  2276,
  458,
  4022,
  85,
  12,
  8,
  6,
  772,
  366,
  222,
  978,
  1807,
  189,
  12,
  1056,
  6,
  28,
  130,
  49,
  3,
  52,
  1,
  124,
  1159,
  98,
  1137,
  20,
  6161,
  186,
  1,
  1,
  44,
  2341,
  1056,
  30,
  18,
  1771,
  236,
  213,
  6,
  1,
  247,
  3,
  1],
 [824,
  655,
  167,
  482,
  542,
  15,
  4334,
  1,
  655,
  167,
  2,
  1,
  256,
  66,
  256,
  141,
  256,
  7,
  865,
  6875,
  655,
  167,
  1584,
  7,
  1700,
  6440,
  406,
  1255,
  866,
  1,
  1,
  4,
  99,
  1,
  523,
  165,
  2269,
  1584,
  6591,
  1,
  1,
  2458,
  1374,
  43,
  1146,
  268,
  1066,
  6649,
  3,
  4,
  5750,
  2138,
  2387,
  6199,
  11,
  1132,
  10,
  1,
  1109,
  106,
  679,
  1756,
  73,
  2723,
  5946,
  322,
  4309,
  1320,
  803,
  1998,
  3089,
  803,
  1,
  87,
  34,
  203,
  1,
  1,
  1,
  9082,
  80,
  736,
  826,
  4479,
  46,
  9083,
  1,
  5276,
  1,
  1030,
  4519,
  1,
  1,
  100,
  1449,
  2654,
  1235,
  308,
  367,
  1,
  6162,
  1,
  68,
  3235,
  5044,
  1151,
  1,
  1179,
  2594,
  9501,
  51,
  41,
  1023,
  1574,
  1621,
  1216,
  61,
  15,
  42,
  5,
  3067,
  1,
  1086,
  9,
  1,
  81,
  1,
  1,
  115,
  31,
  942,
  1114,
  3154,
  37,
  3489,
  1,
  5398,
  22,
  66,
  52,
  1,
  1621,
  634,
  3235,
  235,
  1836,
  341,
  61,
  190,
  246,
  103,
  3235,
  734,
  8,
  1,
  679,
  49,
  6940,
  288,
  18,
  41,
  469,
  2222,
  43,
  1105,
  158,
  3887,
  246,
  178,
  1,
  4,
  1448,
  3116],
 [273,
  5341,
  430,
  2130,
  1,
  40,
  395,
  7,
  188,
  87,
  146,
  2130,
  7,
  11,
  357,
  2130,
  5,
  1,
  839,
  597,
  13,
  8,
  2,
  12,
  122,
  37,
  1,
  688,
  22,
  331,
  102,
  290,
  976,
  117,
  1,
  2,
  3117,
  268,
  1689,
  3081,
  4922,
  265,
  18,
  56,
  990,
  121,
  45,
  1,
  2,
  314,
  9273,
  770,
  232,
  71,
  1115,
  6292,
  165,
  78,
  1,
  27,
  52,
  770,
  44,
  125,
  804,
  1097,
  773,
  373,
  813,
  1706,
  1,
  521,
  5184,
  53,
  59,
  211,
  1179,
  33],
 [301,
  1222,
  2,
  2292,
  8566,
  259,
  33,
  1973,
  17,
  148,
  1,
  958,
  2,
  2864,
  171,
  132,
  53,
  307,
  116,
  1,
  50,
  7,
  1817,
  422,
  7,
  15,
  133,
  3349],
 [25,
  150,
  63,
  10,
  27,
  650,
  2213,
  104,
  114,
  330,
  85,
  225,
  33,
  1900,
  1,
  7,
  1,
  751,
  5,
  320,
  5184,
  466,
  1684,
  5,
  4702,
  2,
  1,
  2,
  25,
  52,
  92,
  5,
  70,
  519,
  2130,
  1689,
  2882,
  1994,
  4632,
  2213,
  52,
  2,
  31,
  1,
  1,
  662,
  22,
  558,
  11,
  326,
  267,
  1900,
  1,
  1,
  85,
  558,
  4,
  16,
  2,
  6441,
  267,
  604,
  127,
  278,
  253,
  127,
  2882,
  273,
  2146,
  42,
  326,
  4702,
  1356,
  3293,
  321,
  102,
  662,
  1,
  274,
  1,
  497,
  5237,
  1977,
  3223,
  5995,
  1060,
  50,
  1458,
  162,
  1618,
  888,
  27,
  629,
  4156,
  5593,
  295,
  332,
  5,
  1633,
  1,
  2823,
  799,
  571,
  1094,
  26,
  1002,
  246,
  2,
  1744,
  1,
  3365,
  24,
  75,
  1346,
  1,
  3366,
  1468,
  1959,
  2130,
  191,
  260,
  90,
  1179,
  33,
  3089,
  466,
  7,
  581,
  2,
  3500,
  4136,
  1,
  1710,
  70,
  59,
  1,
  1,
  2180,
  3500,
  169,
  90,
  17,
  248,
  22,
  148,
  7002,
  185,
  766,
  56,
  26,
  13,
  148,
  306,
  148,
  7002,
  999],
 [146,
  2,
  112,
  1,
  23,
  1777,
  121,
  791,
  7170,
  3367,
  29,
  5314,
  3565,
  342,
  791,
  480,
  37,
  3,
  21,
  14,
  1,
  2,
  94,
  1,
  17,
  49,
  315,
  57,
  1349,
  247,
  43,
  167,
  1287,
  2,
  521,
  580,
  177,
  9,
  333,
  6246,
  1365,
  2277,
  33,
  65,
  719,
  892,
  12,
  2,
  6941,
  37,
  61,
  10,
  54,
  88,
  113,
  780,
  514,
  88,
  5,
  4,
  35,
  7557,
  2,
  112,
  62,
  858,
  11,
  8,
  4,
  647],
 [2580,
  2230,
  12,
  24,
  45,
  1399,
  2580,
  2230,
  1116,
  30,
  72,
  839,
  581,
  1559,
  85,
  1,
  1,
  1951,
  2580,
  366,
  5786,
  8,
  315,
  69,
  2279,
  269,
  831,
  2580,
  2230,
  29,
  77,
  734,
  3327,
  9,
  176,
  3327,
  1,
  1,
  77,
  1,
  2230,
  1157,
  21,
  170,
  2580,
  1,
  21,
  239,
  18,
  1712,
  575,
  3178,
  387,
  72,
  2,
  282,
  488,
  2476,
  320,
  442],
 [1927,
  3855,
  694,
  1,
  997,
  3439,
  216,
  1235,
  308,
  23,
  4,
  875,
  64,
  1,
  1794,
  2854,
  235,
  3045,
  1,
  1,
  1332,
  1,
  54,
  3596,
  1040,
  91,
  284,
  1826,
  2759,
  1627,
  58,
  251,
  1676,
  46,
  2,
  47,
  1,
  219,
  1680,
  2276,
  3,
  1560,
  299,
  2109,
  722,
  83,
  9,
  22,
  43,
  1,
  5868,
  3,
  500,
  82,
  2,
  100,
  6032,
  2214,
  600,
  2,
  2034,
  726,
  1927,
  2705,
  908,
  75,
  84,
  1332,
  6442,
  908,
  231,
  156,
  64,
  1,
  1,
  55,
  1124,
  6,
  2261,
  75,
  2,
  1,
  6,
  34,
  14,
  176,
  125,
  1980,
  1,
  422,
  432,
  70,
  762,
  216,
  1235,
  308,
  341,
  850,
  382,
  103,
  1,
  858,
  268,
  2,
  161,
  5751,
  13,
  1235,
  308,
  9082,
  785,
  1051,
  1927,
  1,
  3072,
  245,
  79,
  470,
  2824,
  6876,
  216,
  1190,
  76,
  241,
  1251,
  1024,
  1207,
  565,
  330,
  48,
  1,
  5,
  2,
  9502,
  63,
  17,
  3454,
  1,
  161,
  1071,
  1759,
  6789,
  73,
  10,
  2115,
  849,
  75,
  200,
  956,
  6650,
  1840,
  3798,
  42,
  5,
  15,
  111,
  1,
  1,
  75,
  8217,
  1927,
  55,
  150,
  14,
  351,
  20,
  5,
  189,
  5,
  1400,
  2,
  2,
  3837,
  1375,
  79,
  1228,
  115,
  150,
  1371,
  222,
  50,
  1,
  1615,
  3,
  344,
  1004,
  463,
  182,
  1772,
  1690,
  1827,
  762,
  849,
  75,
  2684,
  123,
  1244,
  222,
  4349,
  6,
  613,
  3,
  417,
  233,
  621,
  496,
  46,
  813,
  46,
  64,
  5,
  6,
  121,
  10,
  2137,
  46,
  1,
  1615,
  110,
  4582,
  76,
  230,
  40,
  61,
  3904,
  98,
  654,
  91,
  1927,
  711,
  2,
  528,
  216,
  458,
  397,
  1,
  4038,
  5671,
  8,
  7,
  351,
  3,
  45,
  17,
  20,
  369,
  773,
  784,
  17,
  4957,
  1332,
  235,
  216,
  101,
  4870,
  1016,
  479,
  422,
  4,
  155,
  555,
  40,
  2384,
  28,
  2,
  152,
  60,
  8,
  617,
  55,
  3210,
  564],
 [3,
  611,
  35,
  27,
  1,
  838,
  1779,
  242,
  2017,
  4121,
  594,
  96,
  118,
  491,
  1,
  869,
  31,
  1051,
  3179,
  98,
  450,
  180,
  1405,
  1,
  928,
  851,
  393,
  172,
  1,
  1,
  14,
  3597,
  459,
  165,
  458,
  1788,
  3888,
  323,
  1869,
  456,
  5399,
  144,
  222,
  229,
  369,
  331,
  228,
  683,
  1,
  5399,
  28,
  1,
  172,
  8968,
  148,
  26,
  1,
  189,
  4871,
  1194,
  1538,
  103,
  185,
  545,
  3757,
  1,
  1695,
  2032],
 [2,
  4023,
  173,
  339,
  5369,
  333,
  2278,
  8,
  7,
  121,
  91,
  6,
  359,
  434,
  256,
  25,
  773,
  1,
  5,
  67,
  680,
  1318,
  233,
  254,
  1401,
  548,
  1564,
  17,
  2250,
  6646,
  118,
  147,
  919,
  265,
  1628,
  147,
  432,
  45,
  81,
  114,
  2171,
  176,
  1564,
  537,
  352,
  16,
  8764,
  115,
  40,
  1,
  22,
  268,
  8218,
  2,
  1689,
  957,
  373,
  201],
 [172,
  2,
  242,
  382,
  126,
  1,
  35,
  7,
  2239,
  274,
  1,
  39,
  2281,
  102,
  290,
  194,
  1,
  1321,
  1623,
  1,
  3376,
  106,
  172,
  2,
  52,
  234,
  31,
  8219,
  798,
  251,
  113,
  1311,
  12,
  30,
  2565,
  179,
  2450,
  1,
  969,
  1584,
  1080,
  6592,
  1031,
  3778,
  5672,
  1,
  7430,
  1,
  2181,
  969,
  1584,
  172,
  2,
  920,
  1559,
  189,
  98,
  3,
  528,
  86,
  1042,
  1,
  645,
  290,
  138,
  2870,
  64,
  1813,
  1,
  730,
  106,
  969,
  1584,
  17,
  2450,
  172,
  652,
  20,
  7,
  12,
  1507,
  93,
  1,
  7490,
  609,
  1,
  153,
  6592,
  1031,
  346,
  5094,
  2516,
  172,
  1,
  201,
  3163,
  969,
  1584,
  1932,
  9390,
  1203,
  201,
  2363,
  5633,
  204,
  393,
  8567,
  5522,
  153,
  3778,
  5672,
  25,
  4371,
  2637,
  579,
  3992,
  594,
  450,
  62,
  233,
  59,
  155,
  98,
  2003,
  2207,
  5072,
  609,
  8025,
  6293,
  721,
  789,
  1455,
  3,
  2110,
  9179,
  11,
  518,
  1,
  1584,
  413,
  50,
  1,
  158,
  72,
  1,
  361,
  1,
  158,
  1,
  5145,
  1638,
  155,
  3799,
  1256,
  1936,
  1464,
  2207,
  7490,
  335,
  111,
  4703,
  1,
  1999,
  62,
  2706,
  8567,
  1,
  26,
  1665,
  45,
  243,
  1252,
  413,
  4846,
  58,
  1,
  443,
  8567,
  1700,
  163,
  1,
  4923,
  1,
  153,
  1,
  7430,
  190,
  8567,
  138,
  2706,
  62,
  192,
  287,
  2934,
  4583,
  4332,
  5996,
  172,
  92,
  653,
  547,
  1,
  38,
  632,
  3777,
  1311,
  7,
  1076,
  2654,
  1,
  1067,
  3758,
  9,
  1,
  8567,
  5673,
  1065,
  1116,
  5523,
  281,
  68,
  7044,
  1,
  4923,
  1,
  224,
  1128,
  1,
  1,
  2363,
  1,
  4633,
  6443,
  1532,
  2810,
  3490,
  95,
  285,
  2655,
  3368,
  1020,
  172,
  4937,
  1,
  526,
  326,
  344,
  1,
  7929,
  522,
  1,
  1014,
  2125,
  416,
  1,
  201,
  129,
  4122,
  1932,
  9390,
  1,
  155,
  17,
  2516,
  645,
  16,
  7491,
  986,
  9503,
  20,
  172,
  4024,
  72,
  1412,
  4660,
  172,
  1020,
  17,
  388,
  894,
  1,
  134,
  986,
  1,
  1,
  1769,
  1,
  837,
  3730,
  6498,
  1007,
  3,
  695,
  387,
  1,
  144,
  8390,
  1184,
  45,
  1277,
  1549,
  5524,
  9,
  34,
  12,
  1,
  8567,
  8765,
  8220,
  1375,
  329,
  44,
  3,
  72,
  1,
  3224,
  1,
  11,
  1678,
  750,
  358,
  26,
  666,
  5674,
  750,
  247,
  1,
  876,
  969,
  1584,
  938,
  3905,
  4872,
  691,
  3455,
  172,
  319,
  788,
  1343,
  904,
  152,
  2495,
  23,
  251,
  1,
  155,
  30,
  20,
  2905,
  863,
  172,
  920,
  1613,
  3101,
  273,
  1,
  3478],
 [6877,
  1,
  2699,
  1813,
  1,
  8766,
  6688,
  651,
  535,
  2295,
  522,
  2,
  634,
  42,
  1818,
  1520,
  1,
  2086,
  6593,
  796,
  609,
  4583,
  1,
  2171,
  1155,
  185,
  44,
  1622,
  1387,
  399,
  1562,
  1722,
  1,
  1046,
  2147,
  1081,
  1,
  206,
  425,
  2167,
  440,
  1059,
  399,
  95,
  1,
  190,
  399,
  4958,
  4480,
  1,
  2674,

In [45]:
sequences=Tokenizer.texts_to_sequences(dfmovie["review"])

In [46]:
dfmovie["review"]

0        one reviewer mentioned watching 1 oz episode h...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically family little boy jake think zombie ...
4        petter matteis love time money visually stunni...
                               ...
49995    thought movie right good job creative original...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary school nu...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movie high art fan expec...
Name: review, Length: 50000, dtype: str

In [47]:
len(dfmovie["review"][0].split())

163

In [48]:
sequences[0]

[4,
 994,
 921,
 67,
 398,
 3080,
 166,
 2878,
 101,
 481,
 465,
 6821,
 25,
 27,
 2952,
 3080,
 4936,
 1,
 16,
 467,
 123,
 101,
 240,
 31,
 1544,
 24,
 6245,
 5182,
 1,
 24,
 881,
 1996,
 2029,
 617,
 271,
 467,
 3098,
 217,
 243,
 1,
 357,
 3080,
 8966,
 245,
 1,
 6197,
 2331,
 570,
 1,
 733,
 1221,
 1,
 383,
 4266,
 1926,
 1018,
 1927,
 1795,
 793,
 231,
 1,
 1,
 220,
 4069,
 383,
 233,
 1,
 3756,
 1,
 6646,
 1163,
 842,
 2238,
 1,
 1,
 206,
 3796,
 6647,
 1623,
 7692,
 7370,
 41,
 130,
 1,
 6,
 40,
 177,
 1036,
 24,
 531,
 85,
 31,
 24,
 6,
 2382,
 679,
 90,
 238,
 3885,
 2275,
 155,
 679,
 1112,
 679,
 1,
 806,
 93,
 25,
 166,
 48,
 112,
 2952,
 1422,
 1997,
 18,
 40,
 1393,
 181,
 1309,
 948,
 3080,
 87,
 9080,
 220,
 423,
 1229,
 467,
 467,
 5866,
 6338,
 1898,
 2673,
 1,
 4844,
 259,
 435,
 10,
 142,
 19,
 8763,
 619,
 590,
 4844,
 527,
 1018,
 5013,
 531,
 323,
 552,
 1146,
 1018,
 370,
 67,
 3080,
 100,
 306,
 3404,
 2962,
 1,
 10,
 760,
 3626,
 338]

In [49]:
len(sequences[0])

163

In [50]:
len(sequences[1]),len(sequences[2]),len(sequences[3]),len(sequences[4])    #each sequence has different lengths to solve that we use padding

(84, 85, 64, 125)

In [51]:
#max([len(s) for s in sequences])

In [52]:
#np.mean([len(s) in sequences])

#Padding - Padding is the process of adding extra values (usually 0s) to sequences so that all sequences have the same length.

there are 2 types of padding pre and post padding

In [53]:
from tensorflow.keras.preprocessing.sequence    import pad_sequences

In [54]:
padded_sequence=pad_sequences(sequences ,maxlen=300,padding="post",truncating="post")

In [55]:
padded_sequence

array([[   4,  994,  921, ...,    0,    0,    0],
       [ 281,   45,  228, ...,    0,    0,    0],
       [  91,  281,   26, ...,    0,    0,    0],
       ...,
       [2930, 3869,    1, ...,    0,    0,    0],
       [  70, 2730,  749, ...,    0,    0,    0],
       [   4, 5223,  105, ...,    0,    0,    0]],
      shape=(50000, 300), dtype=int32)

In [56]:
padded_sequence.shape

(50000, 300)

In [57]:
X=padded_sequence.copy()

In [58]:
X.shape

(50000, 300)

#perform label encoding on dependent column to convert it into numerical form (y=sentiment)

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
label=LabelEncoder()

In [61]:
label

LabelEncoder()

In [62]:
label.fit(dfmovie["sentiment"])

LabelEncoder()

In [63]:
ary=label.transform(dfmovie["sentiment"])

In [64]:
label.classes_

array(['negative', 'positive'], dtype=object)

In [65]:
dfmovie["sentiment"]=ary

In [66]:
dfmovie.head()

                                              review  sentiment
0  one reviewer mentioned watching 1 oz episode h...          1
1  wonderful little production filming technique ...          1
2  thought wonderful way spend time hot summer we...          1
3  basically family little boy jake think zombie ...          0
4  petter matteis love time money visually stunni...          1

In [67]:
y=dfmovie["sentiment"]

Imbalance

In [68]:
y.value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

Data Splitting

In [69]:
from sklearn.model_selection    import train_test_split

In [70]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [71]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((40000, 300), (10000, 300), (40000,), (10000,))

Model  Building

In [72]:
from tensorflow.keras.models import Sequential

In [103]:
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense,Dropout

In [104]:
rnn_model=Sequential()

In [105]:
rnn_model.add(Embedding(input_dim=10000,output_dim=128,input_length=(300)))

In [106]:
rnn_model.add(SimpleRNN(128,activation="tanh"))

In [107]:
rnn_model.add(Dense(1,activation="sigmoid"))

In [108]:
rnn_model.add(Dropout(0.5))

Compile

In [109]:
import warnings
warnings.filterwarnings('ignore')

In [110]:
rnn_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [111]:
rnn_model.fit(X_train,y_train,epochs=5,batch_size=64)

Epoch 1/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 49s 77ms/step - accuracy: 0.4977 - loss: 8.0518
Epoch 2/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 48s 77ms/step - accuracy: 0.4943 - loss: 8.1068
Epoch 3/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 49s 78ms/step - accuracy: 0.5020 - loss: 7.9838
Epoch 4/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 49s 78ms/step - accuracy: 0.4986 - loss: 8.0373
Epoch 5/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 48s 77ms/step - accuracy: 0.5032 - loss: 7.9639